---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
data:
  DATABASE_URL: "postgresql://postgres:jIfz7CpD4n@my-postgres-postgresql.default.svc.cluster.local:5432/postgres" 
  SECRET_KEY: "your_secret_key_here" 
  DEBUG: "False"
  ALLOWED_HOSTS: "127.0.0.1,localhost,star-burger.test"
...

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
...

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
...


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: wombatoff/django-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: ALLOWED_HOSTS
          volumeMounts:
            - name: static-volume
              mountPath: /code/static
            - name: media-volume
              mountPath: /code/media
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: django-static-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: django-media-pvc
...

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
...

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
spec:
  rules:
  - host: "star-burger.test"
    http:
      paths:
      - pathType: Prefix
        path: "/admin"
        backend:
          service:
            name: django-service
            port:
              number: 80
...