apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  template:
    metadata:
      labels:
        app: django-migrate-job
    spec:
      containers:
        - name: django-app
          image: wombatoff/django-app:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-app-config
                  key: ALLOWED_HOSTS
      restartPolicy: OnFailure
